### ISSUE TITLE
Get an exception on deserialization

### ISSUE THREAD

**Issue by beenokle** [yyuu/jetty-nosql-memcached#13]
I've got two jetty nodes.
Different virtual machines use the same JVM and same jetty (8.1.9)

When accessed one node - it saved session to memcached without problem - trying to access another node - get this exception.

I don't have any ideas

```
Caused by: 
org.eclipse.jetty.nosql.kvs.session.TranscoderException: java.io.StreamCorruptedException: invalid stream header: 7A393973
	at org.eclipse.jetty.nosql.kvs.session.serializable.SerializableTranscoder.decode(SerializableTranscoder.java:49)
	at org.eclipse.jetty.nosql.kvs.session.serializable.SerializableSessionFactory.unpack(SerializableSessionFactory.java:36)
	at org.eclipse.jetty.nosql.kvs.session.AbstractSessionFactory.unpack(AbstractSessionFactory.java:65)
	at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.getKey(KeyValueStoreSessionManager.java:341)
	at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.loadSession(KeyValueStoreSessionManager.java:240)
	at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.getSession(KeyValueStoreSessionManager.java:233)
	at org.eclipse.jetty.server.session.AbstractSessionManager.getHttpSession(AbstractSessionManager.java:313)
	at org.eclipse.jetty.server.session.SessionHandler.checkRequestedSessionId(SessionHandler.java:279)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:159)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:256)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:932)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:609)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:662)
Caused by: 
java.io.StreamCorruptedException: invalid stream header: 7A393973
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:782)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:279)
	at org.eclipse.jetty.nosql.kvs.session.serializable.ClassLoadingObjectInputStream.<init>(ClassLoadingObjectInputStream.java:19)
	at org.eclipse.jetty.nosql.kvs.session.serializable.SerializableTranscoder.decode(SerializableTranscoder.java:46)
	at org.eclipse.jetty.nosql.kvs.session.serializable.SerializableSessionFactory.unpack(SerializableSessionFactory.java:36)
	at org.eclipse.jetty.nosql.kvs.session.AbstractSessionFactory.unpack(AbstractSessionFactory.java:65)
	at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.getKey(KeyValueStoreSessionManager.java:341)
	at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.loadSession(KeyValueStoreSessionManager.java:240)
	at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.getSession(KeyValueStoreSessionManager.java:233)
	at org.eclipse.jetty.server.session.AbstractSessionManager.getHttpSession(AbstractSessionManager.java:313)
	at org.eclipse.jetty.server.session.SessionHandler.checkRequestedSessionId(SessionHandler.java:279)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:159)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:256)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:932)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:609)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by yyuu** [comment]
This might be solved by #29 and #30. Please send me back some PR if you still have problem.
