### ISSUE TITLE
AbstractMethodError in Jetty 9.2.3

### ISSUE THREAD

**Issue by 0zores** [yyuu/jetty-nosql-memcached#27]
Hi, yyuu

I'm trying to use this library in Jetty 9.2.3, but the application of my customer get this exception described below when try to get the session from memcached.

`15:17:38,282  WARN  [ServletHandler] Error for /contact-center/
java.lang.AbstractMethodError: org.eclipse.jetty.server.session.AbstractSession.getAttributeMap()Ljava/util/Map;
        at org.eclipse.jetty.server.session.AbstractSession.willPassivate(AbstractSession.java:616)
        at org.eclipse.jetty.nosql.kvs.KeyValueStoreSessionManager.save(KeyValueStoreSessionManager.java:136)
        at org.eclipse.jetty.nosql.NoSqlSession.save(NoSqlSession.java:139)
        at org.eclipse.jetty.nosql.NoSqlSession.<init>(NoSqlSession.java:48)
        at org.eclipse.jetty.nosql.NoSqlSessionManager.newSession(NoSqlSessionManager.java:126)
        at org.eclipse.jetty.server.session.AbstractSessionManager.newHttpSession(AbstractSessionManager.java:564)
        at org.eclipse.jetty.server.Request.getSession(Request.java:1406)
        at org.eclipse.jetty.server.Request.getSession(Request.java:1379)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:279)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:279)
        at org.springframework.security.web.savedrequest.HttpSessionRequestCache.saveRequest(HttpSessionRequestCache.java:40)
        at org.springframework.security.web.access.ExceptionTranslationFilter.sendStartAuthentication(ExceptionTranslationFilter.java:184)
        at org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:168)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:131)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at br.com.abril.ass.web.filter.AssApplicationFilter.doFilter(AssApplicationFilter.java:61)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)
15:17:38,287  DEBUG [HttpConnection] org.eclipse.jetty.server.HttpConnection$SendCallback@737acc77[ITERATING][i=ResponseInfo{HTTP/1.1 500 null,6002,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@5ac84ba8] generate: NEED_HEADER (null,[p=0,l=6002,c=7284,r=6002],true)@START`

** This is one part of jetty.xml **

`
...
    
    
    

    <Set name="sessionIdManager">
          <New id="memcachedSessionIdManager" class="org.eclipse.jetty.nosql.memcached.MemcachedSessionIdManager">
                <Arg><Ref id="Server" /></Arg>
                <Set name="serverString">MCHOM01:11211</Set>
                <Set name="keyPrefix">session:</Set>
          </New>
    </Set>
    <Call name="setAttribute">
          <Arg>memcachedSessionIdManager</Arg>
          <Arg><Ref id="memcachedSessionIdManager" /></Arg>
    </Call>
`

** And this is the {webapp}.xml **

`
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN" "http://jetty.eclipse.org/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/contact-center</Set>
  <Set name="war"><SystemProperty name="jetty.home" default="."/>/JEHOM07/webapps/contact-center.war</Set>
  <Ref name="Server" id="Server">
    <Call id="sessionIdManager" name="getAttribute">
      <Arg>memcachedSessionIdManager</Arg>
    </Call>
  </Ref>
  <Set name="sessionHandler">
    <New class="org.eclipse.jetty.server.session.SessionHandler">
      <Arg>
        <New id="memcachedSessionManager" class="org.eclipse.jetty.nosql.memcached.MemcachedSessionManager">
          <Set name="sessionIdManager">
            <Ref id="memcachedSessionIdManager" />
          </Set>
          <Set name="sessionFactory">
            <New class="org.eclipse.jetty.nosql.kvs.session.xstream.XStreamSessionFactory" />
          </Set>
        </New>
      </Arg>
    </New>
  </Set>
</Configure>
`

**Comment by efiandrzej** [comment]
Hello,
Did You manage to solve the problem?
I got the same on jetty-9.2.10

**Comment by jasollien** [comment]
Hi, any progress on this? I have the same problem

**Comment by 0zores** [comment]
Hi, guys, sorry for the late reply, I was very busy these days.
I solve the problem making some ugly steps: :-)

- Cloning the git repository at Eclipse
- Converting to Maven Project
- Changing this property in pom.xml
	From:	<jetty.version>9.0.3.v20130506</jetty.version>
	To:	        <jetty.version>9.2.3.v20140905</jetty.version>
	The correct version number, you can get in the maven repository  
	(http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server)
- Following the Eclipse hints to correct code errors 
- Building the project again skipping the tests (maven clean package -DskipTests=true)
- Putting the output jar file in my environment 
- Configuring the jetty's XML as described in README.md

You must repeat the 3rd step and the followings, if you update your jetty version

I already have a jar file ready for the 9.2.3 version in this location
https://app.box.com/s/fd3rtaqyrd4hlu7qbmtehuh175gziayw
